source 'https://rubygems.org'

ruby "2.1.1" # gem install bundler --pre

gem 'guard'
gem 'guard-coffeescript'
gem 'guard-sass'
gem 'guard-rake'
gem 'therubyracer'
gem "actionpack", '>= 3.2.13'
gem "activesupport", '>= 3.2.13'
gem 'sinatra'
gem 'sprockets'
gem 'sprockets-sass'
gem 'yui-compressor'
gem 'uglifier'
gem 'html_compressor'
gem 'haml'
gem 'tilt'
gem 'execjs'
gem 'compass'
gem 'vegas'
gem 'erubis'
gem 'zurb-foundation', '3.2.5'